# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bgrafana_api.models.frame import Frame  # noqa: E501

class TestFrame(unittest.TestCase):
    """Frame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Frame:
        """Test Frame
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Frame`
        """
        model = Frame()  # noqa: E501
        if include_optional:
            return Frame(
                fields = [
                    bgrafana_api.models.field_represents_a_typed_column_of_data_within_a_frame/.Field represents a typed column of data within a Frame.(
                        config = bgrafana_api.models.field_config_represents_the_display_properties_for_a_field/.FieldConfig represents the display properties for a Field.(
                            color = bgrafana_api.models.color.color(), 
                            custom = bgrafana_api.models.custom.custom(), 
                            decimals = 56, 
                            description = '', 
                            display_name = '', 
                            display_name_from_ds = '', 
                            filterable = True, 
                            interval = 1.337, 
                            links = [
                                bgrafana_api.models.data_link.DataLink(
                                    target_blank = True, 
                                    title = '', 
                                    url = '', )
                                ], 
                            mappings = [
                                bgrafana_api.models.value_mapping.ValueMapping()
                                ], 
                            max = 1.337, 
                            min = 1.337, 
                            no_value = '', 
                            path = '', 
                            thresholds = bgrafana_api.models.thresholds_config.ThresholdsConfig(
                                mode = '', 
                                steps = [
                                    bgrafana_api.models.threshold.Threshold(
                                        color = '', 
                                        state = '', 
                                        value = 1.337, )
                                    ], ), 
                            type = bgrafana_api.models.field_type_config.FieldTypeConfig(
                                enum = bgrafana_api.models.enum_field_config.EnumFieldConfig(
                                    color = [
                                        ''
                                        ], 
                                    description = [
                                        ''
                                        ], 
                                    icon = [
                                        ''
                                        ], 
                                    text = [
                                        ''
                                        ], ), ), 
                            unit = '', 
                            writeable = True, ), 
                        labels = {
                            'key' : ''
                            }, 
                        name = '', )
                    ],
                meta = bgrafana_api.models.frame_meta_matches:.FrameMeta matches:(
                    channel = '', 
                    custom = null, 
                    data_topic = '', 
                    executed_query_string = '', 
                    notices = [
                        bgrafana_api.models.notice_provides_a_structure_for_presenting_notifications_in_grafana's_user_interface/.Notice provides a structure for presenting notifications in Grafana's user interface.(
                            inspect = 56, 
                            link = '', 
                            severity = 56, 
                            text = '', )
                        ], 
                    path = '', 
                    path_separator = '', 
                    preferred_visualisation_type = '', 
                    stats = [
                        bgrafana_api.models.query_stat_is_used_for_storing_arbitrary_statistics_metadata_related_to_a_query_and_its_result,_e/g/_total_request_time,_data_processing_time/.QueryStat is used for storing arbitrary statistics metadata related to a query and its result, e.g. total request time, data processing time.(
                            color = bgrafana_api.models.color.color(), 
                            custom = bgrafana_api.models.custom.custom(), 
                            decimals = 56, 
                            description = '', 
                            display_name = '', 
                            display_name_from_ds = '', 
                            filterable = True, 
                            interval = 1.337, 
                            links = [
                                bgrafana_api.models.data_link.DataLink(
                                    target_blank = True, 
                                    title = '', 
                                    url = '', )
                                ], 
                            mappings = [
                                bgrafana_api.models.value_mapping.ValueMapping()
                                ], 
                            max = 1.337, 
                            min = 1.337, 
                            no_value = '', 
                            path = '', 
                            thresholds = bgrafana_api.models.thresholds_config.ThresholdsConfig(
                                mode = '', 
                                steps = [
                                    bgrafana_api.models.threshold.Threshold(
                                        color = '', 
                                        state = '', 
                                        value = 1.337, )
                                    ], ), 
                            type = bgrafana_api.models.field_type_config.FieldTypeConfig(
                                enum = bgrafana_api.models.enum_field_config.EnumFieldConfig(
                                    color = [
                                        ''
                                        ], 
                                    description = [
                                        ''
                                        ], 
                                    icon = [
                                        ''
                                        ], 
                                    text = [
                                        ''
                                        ], ), ), 
                            unit = '', 
                            value = 1.337, 
                            writeable = True, )
                        ], 
                    type = '', 
                    type_version = [
                        56
                        ], ),
                name = '',
                ref_id = ''
            )
        else:
            return Frame(
        )
        """

    def testFrame(self):
        """Test Frame"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
